class MyError extends Exception

func test(_e: xfer[Exception])
	try
		raise(_e)
	except MyError as e
		print("MyError " + str(e))
#	except Exception as e
#		print("Exception " + str(e))

func main()
	try
		test(new MyError("aaa"))
		test(new Exception("bbb"))
	except Exception as e
		print("end: " + str(e))
