func main()
	try
		raise(new Exception)
	except
		print("catch...")
