class MyError extends Exception

void test(Exception *_e)
	try
		raise(_e)
	except MyError as e
		print("MyError " + e.message())
#	except Exception as e
#		print("Exception " + e.message())

void main()
	try
		test(new MyError("aaa"))
		test(new Exception("bbb"))
	except Exception as e
		print("end: " + e.message())
